# Generated by Django 4.2.10 on 2025-08-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image_links',
        ),
    ]
