# Generated by Django 3.2.24 on 2025-06-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
