# Generated by Django 4.2.10 on 2025-08-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_image_url_product_image_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_links',
            new_name='image_url',
        ),
    ]
