# Generated by Django 4.2.10 on 2025-08-15 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_image_links_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('image_url', models.URLField(max_length=1000, verbose_name='URL изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_search__186618_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_categor_640ae3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_created_587a36_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product'),
        ),
    ]
