# Generated by Django 4.2.10 on 2025-08-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wildberries_card_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по карте Wildberries'),
        ),
    ]
