# Generated by Django 4.2.10 on 2025-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
