# Generated by Django 4.2.10 on 2025-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_has_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
