# Generated by Django 4.2.10 on 2025-08-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_productimage_options_productimage_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_wb_card_discount',
            field=models.BooleanField(default=False, verbose_name='Есть скидка по карте Wildberries'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_image',
            field=models.BooleanField(default=False, verbose_name='Есть изображения'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_id'], name='app_product_product_d7143d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='app_product_categor_640ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['search_query'], name='app_product_search__186618_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['has_wb_card_discount'], name='app_product_has_wb__86c435_idx'),
        ),
    ]
