# Generated by Django 4.2.10 on 2025-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_has_wb_card_discount_alter_product_has_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_size',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_type',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=200, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='app_product_is_avai_9f2871_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='app_product_brand_d9c5aa_idx'),
        ),
    ]
