# Generated by Django 4.2.10 on 2025-08-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', 'id'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_is_avai_9f2871_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_brand_d9c5aa_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
