# Generated by Django 4.2.10 on 2025-08-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_is_available_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_wb_card_payment',
            field=models.BooleanField(default=False, verbose_name='Доступна оплата картой Wildberries'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['has_wb_card_payment'], name='app_product_has_wb__647ffc_idx'),
        ),
    ]
