# Generated by Django 4.2.10 on 2025-08-21 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_product_has_wb_card_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField()),
                ('last_parsed', models.DateTimeField(blank=True, null=True)),
                ('total_products', models.IntegerField(default=0)),
                ('pages_parsed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('shown_to_user', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('search_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.searchsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='searchsession',
            index=models.Index(fields=['user', 'query'], name='app_searchs_user_id_da5c11_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsession',
            index=models.Index(fields=['last_active'], name='app_searchs_last_ac_fba5ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='searchsession',
            unique_together={('user', 'query', 'category')},
        ),
        migrations.AddIndex(
            model_name='productsearchresult',
            index=models.Index(fields=['search_session', 'parsed_at'], name='app_product_search__f82844_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsearchresult',
            unique_together={('search_session', 'product')},
        ),
    ]
