# Generated by Django 4.2.10 on 2025-08-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_searchsession_productsearchresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_query',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Поисковый запрос'),
        ),
    ]
