# Generated by Django 4.2.10 on 2025-08-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_product_is_cached_product_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_cached',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='product',
            name='search_query',
            field=models.CharField(max_length=200, verbose_name='Поисковый запрос'),
        ),
    ]
