# Generated by Django 4.2.10 on 2025-08-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_product_is_cached_remove_product_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_categor_640ae3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_search__186618_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_query',
        ),
    ]
