# Generated by Django 4.2.10 on 2025-08-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_product_app_product_categor_640ae3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_query',
            field=models.CharField(default='', max_length=200, verbose_name='Поисковый запрос'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['search_query'], name='app_product_search__186618_idx'),
        ),
    ]
