# Generated by Django 4.2.10 on 2025-08-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_product_search_query_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsearchresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productsearchresult',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsearchresult',
            name='search_session',
        ),
        migrations.AlterUniqueTogether(
            name='searchsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='searchsession',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_product_d7143d_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_has_wb__86c435_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_has_wb__647ffc_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default='', max_length=100, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace',
            field=models.CharField(choices=[('WB', 'Wildberries'), ('OZ', 'Ozon')], default='', max_length=2, verbose_name='Маркетплейс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оригинальная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на товар'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('marketplace',)},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['marketplace'], name='app_product_marketp_2d0464_idx'),
        ),
        migrations.DeleteModel(
            name='ProductSearchResult',
        ),
        migrations.DeleteModel(
            name='SearchSession',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_wb_card_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_wb_card_payment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wildberries_card_price',
        ),
    ]
