# Generated by Django 4.2.10 on 2025-08-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_productsearchresult_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_marketp_2d0464_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('article', 'marketplace')},
        ),
        migrations.AddField(
            model_name='product',
            name='card_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по карте'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['article', 'marketplace'], name='app_product_article_b0fdb1_idx'),
        ),
    ]
