# Generated by Django 4.2.10 on 2025-08-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_product_app_product_marketp_2d0464_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_article_b0fdb1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='has_wb_card_discount',
            field=models.BooleanField(default=False, verbose_name='Есть скидка по карте Wildberries'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_wb_card_payment',
            field=models.BooleanField(default=False, verbose_name='Доступна оплата картой Wildberries'),
        ),
        migrations.AddField(
            model_name='product',
            name='wildberries_card_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по карте Wildberries'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(max_length=1000, verbose_name='Ссылка на товар'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_id'], name='app_product_product_d7143d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['has_wb_card_discount'], name='app_product_has_wb__86c435_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['has_wb_card_payment'], name='app_product_has_wb__647ffc_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='article',
        ),
        migrations.RemoveField(
            model_name='product',
            name='card_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marketplace',
        ),
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
    ]
