# Generated by Django 4.2.10 on 2025-08-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_product_app_product_article_b0fdb1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketplace',
            field=models.CharField(choices=[('wildberries', 'Wildberries'), ('ozon', 'Ozon')], default='wildberries', max_length=20, verbose_name='Маркетплейс'),
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой Ozon'),
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Ozon'),
        ),
    ]
