# Generated by Django 4.2.10 on 2025-08-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_product_marketplace_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsearchresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productsearchresult',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsearchresult',
            name='search_session',
        ),
        migrations.AlterUniqueTogether(
            name='searchsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='searchsession',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_search__186618_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_product_d7143d_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_has_wb__647ffc_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='has_ozon_card_discount',
            field=models.BooleanField(default=False, verbose_name='Есть скидка по карте Ozon'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_ozon_card_payment',
            field=models.BooleanField(default=False, verbose_name='Доступна оплата картой Ozon'),
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_card_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по карте Ozon'),
        ),
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('WB', 'Wildberries'), ('OZ', 'Ozon')], default='WB', max_length=2, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=100, verbose_name='ID товара'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('platform', 'product_id')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['platform', 'product_id'], name='app_product_platfor_3c1649_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['platform', 'search_query'], name='app_product_platfor_65e6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['platform'], name='app_product_platfor_e1ecd2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['has_ozon_card_discount'], name='app_product_has_ozo_d30dfe_idx'),
        ),
        migrations.DeleteModel(
            name='ProductSearchResult',
        ),
        migrations.DeleteModel(
            name='SearchSession',
        ),
    ]
