# Generated by Django 4.2.10 on 2025-09-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_productsearchresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('WB', 'Wildberries'), ('OZ', 'Ozon')], default='WB', max_length=10, verbose_name='Платформа'),
        ),
    ]
