# Generated by Django 4.2.10 on 2025-09-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_product_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('WB', 'Wildberries'), ('OZ', 'Ozon')], default='WB', max_length=40, verbose_name='Платформа'),
        ),
    ]
