# Generated by Django 4.2.10 on 2025-09-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_telegramuser_usersession_usersearchhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_premium',
        ),
    ]
