# Generated by Django 4.2.10 on 2025-09-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_telegramuser_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='PriceAlert',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
        migrations.DeleteModel(
            name='UserSearchHistory',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
